--------------------------------------------------------
--  File created - Friday-June-14-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure SP_SIM_SYS_REQ_TXN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HEIS_SU"."SP_SIM_SYS_REQ_TXN" 
as
---SP TO SIMULATE REQUEST TRANSACTION ENTRY INTO HDM
--DATE: 05-JUN-2013
--CURSOR TO PICK ALL UNPROCESSED TRANSACTIONS IN TEMP TABLE.
  cursor C1
  is
    select TRT.rowid,
      TRT.REQUEST_CODE,
      TRT.CLIENT_CODE,
      TRT.CLIENT_NAME,
      TRT.APPLICATION_ID,
      TRT.AMOUNT,
      TRT.TYPE_OF_REQUEST,
      TRT.MAKER_ID,
      TRT.CR_DT,
      TRT.CR_BY,
      TRT.ACTIVE,
      TRT.EMAIL_ID,
      TRT.EMAIL_TO_BE_SENT_TO,
      TRT.INS_UPD_FLAG
    from TEMP_REQUEST_TXN TRT
    where TRT.PROCESS_FLAG='N'
    ORDER BY TRT.INS_UPD_FLAG;
begin
  for INSERT_REC in C1
  LOOP
  IF insert_rec.ins_upd_flag = 'I' THEN
  --INSERT INTO HI_REQEUST_TXN
    insert
    into HI_REQUEST_TXN
      (
        REQUEST_CODE,
        CLIENT_CODE,
        CLIENT_NAME,
        APPLICATION_ID,
        AMOUNT,
        TYPE_OF_REQUEST,
        MAKER_ID,
        CR_DT,
        CR_BY,
        ACTIVE
      )
      values
      (
        INSERT_REC.REQUEST_CODE,
        INSERT_REC.CLIENT_CODE,
        INSERT_REC.CLIENT_NAME,
        INSERT_REC.APPLICATION_ID,
        INSERT_REC.AMOUNT,
        INSERT_REC.TYPE_OF_REQUEST,
        INSERT_REC.MAKER_ID,
        --INSERT_REC.CR_DT,
        sysdate, -- now the cr date of Temp_REQ_TXN and REQ_TXN will not be same
        INSERT_REC.CR_BY,
        INSERT_REC.ACTIVE
      );
     
     END IF; 
      --UPDATE THE PROCESS FLAG.
    update TEMP_REQUEST_TXN a
    set a.PROCESS_FLAG = 'Y'
    where a.rowid      = INSERT_REC.rowid;
  
--if ins_upd_flag     
INSERT INTO TEMP_RESPONSE_FOR_SYSREQUEST
(ORG_ID,
MSG_SUBJECT,
MSG_CONTENT,
MSG_ENDOFMAIL,
MSG_TO_BE_SENT_TO,
PROCESS_FLAG)
VALUES
(9000, -- Hardcoded for now
'Your email Request for '|| INSERT_REC.CLIENT_NAME,
'We are happy to inform you that your email '||
to_char(INSERT_REC.EMAIL_ID) || ' has been processed. The Request No generated by the system is '||INSERT_REC.REQUEST_CODE
||'. Please use the same for future reference.',
'Regards',
INSERT_REC.EMAIL_TO_BE_SENT_TO,
'N');

  end LOOP;
end;

/
