--------------------------------------------------------
--  File created - Friday-June-14-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEMP_RESPONSE_FOR_SYSREQUEST
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" 
   (	"ORG_ID" NUMBER(8,0), 
	"MSG_SUBJECT" VARCHAR2(4000 BYTE), 
	"MSG_CONTENT" VARCHAR2(4000 BYTE), 
	"MSG_ENDOFMAIL" VARCHAR2(4000 BYTE), 
	"MSG_TO_BE_SENT_TO" VARCHAR2(4000 BYTE), 
	"PROCESS_FLAG" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
REM INSERTING into HEIS_SU.TEMP_RESPONSE_FOR_SYSREQUEST
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table TEMP_RESPONSE_FOR_SYSREQUEST
--------------------------------------------------------

  ALTER TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" MODIFY ("ORG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" MODIFY ("MSG_SUBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" MODIFY ("MSG_CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" MODIFY ("MSG_ENDOFMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" MODIFY ("MSG_TO_BE_SENT_TO" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."TEMP_RESPONSE_FOR_SYSREQUEST" MODIFY ("PROCESS_FLAG" NOT NULL ENABLE);

