--------------------------------------------------------
--  File created - Friday-June-14-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UM_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."UM_EMPLOYEE" 
   (	"ORG_ID" NUMBER(8,0), 
	"EMPLOYEE_ID" VARCHAR2(50 BYTE), 
	"EMP_NAME" VARCHAR2(4000 BYTE), 
	"EMP_NAME2" VARCHAR2(4000 BYTE), 
	"LEVEL_ID" NUMBER(12,0), 
	"LEVEL_PRED_ID" VARCHAR2(50 BYTE), 
	"EMP_TYPE" VARCHAR2(100 BYTE), 
	"RELATIONSHIP_SINCE" DATE, 
	"RELATIONSHIP_ENDED" VARCHAR2(4000 BYTE), 
	"ROLE" VARCHAR2(500 BYTE), 
	"DESIGNATION" VARCHAR2(500 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(50 BYTE), 
	"GROSS_YEARLY_SAL" NUMBER(12,0), 
	"EMP_EMAIL_ID1" VARCHAR2(50 BYTE), 
	"EMP_EMAIL_ID2" VARCHAR2(50 BYTE), 
	"EMP_MOBILE_NO1" NUMBER(16,0), 
	"EMP_MOBILE_NO2" NUMBER(16,0), 
	"FF_N1" NUMBER(16,2), 
	"FF_N2" NUMBER(16,2), 
	"FF_N3" NUMBER(16,2), 
	"FF_N4" NUMBER(16,2), 
	"FF_N5" NUMBER(16,2), 
	"FF_VC1" VARCHAR2(500 BYTE), 
	"FF_VC2" VARCHAR2(500 BYTE), 
	"FF_VC3" VARCHAR2(500 BYTE), 
	"FF_VC4" VARCHAR2(500 BYTE), 
	"FF_VC5" VARCHAR2(500 BYTE), 
	"FF_D1" DATE, 
	"FF_D2" DATE, 
	"FF_D3" DATE, 
	"FF_D4" DATE, 
	"FF_D5" DATE, 
	"CR_ID" VARCHAR2(50 BYTE), 
	"CR_DT" DATE, 
	"UPD_ID" VARCHAR2(50 BYTE), 
	"UPD_DT" DATE, 
	"ACTIVE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
 

   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."ORG_ID" IS 'Supervisor Employee id';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."EMPLOYEE_ID" IS 'As given by source';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."EMP_TYPE" IS 'CONSULTANT/EMPLOYEE/TEMPORARY';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."RELATIONSHIP_SINCE" IS 'Date of Joining';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_N1" IS 'Flexi Field - Number type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_N2" IS 'Flexi Field - Number type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_N3" IS 'Flexi Field - Number type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_N4" IS 'Flexi Field - Number type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_N5" IS 'Flexi Field - Number type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_VC1" IS 'Flexi Field - Char type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_VC2" IS 'Flexi Field - Char type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_VC3" IS 'Flexi Field - Char type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_VC4" IS 'Flexi Field - Char type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_VC5" IS 'Flexi Field - Char type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_D1" IS 'Flexi Field - Date type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_D2" IS 'Flexi Field - Date type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_D3" IS 'Flexi Field - Date type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_D4" IS 'Flexi Field - Date type';
 
   COMMENT ON COLUMN "HEIS_SU"."UM_EMPLOYEE"."FF_D5" IS 'Flexi Field - Date type';
REM INSERTING into HEIS_SU.UM_EMPLOYEE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UE_CK_EMPLOYEE_ORG_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HEIS_SU"."UE_CK_EMPLOYEE_ORG_ID" ON "HEIS_SU"."UM_EMPLOYEE" ("ORG_ID", "EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
--------------------------------------------------------
--  Constraints for Table UM_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("ORG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("EMP_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("LEVEL_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("ROLE" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("DESIGNATION" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("CR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("CR_DT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" MODIFY ("ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" ADD CONSTRAINT "UE_CHK_ACTIVE" CHECK (ACTIVE in ('Y','N')) ENABLE;
 
  ALTER TABLE "HEIS_SU"."UM_EMPLOYEE" ADD CONSTRAINT "UE_CK_EMPLOYEE_ORG_ID" PRIMARY KEY ("ORG_ID", "EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS"  ENABLE;

