--------------------------------------------------------
--  File created - Friday-June-14-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UM_EMAIL_RESPONSE
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" 
   (	"ORG_ID" NUMBER(8,0), 
	"RESPONSE_ID" NUMBER(8,0), 
	"SCENARIO" VARCHAR2(4000 BYTE), 
	"APPLSTAGE" VARCHAR2(50 BYTE), 
	"SUCCESS_FLAG" VARCHAR2(1 BYTE), 
	"TYPE_OF_MSG" VARCHAR2(50 BYTE), 
	"MSG_SUBJECT1" VARCHAR2(4000 BYTE), 
	"MSG_SUBJECT2" VARCHAR2(4000 BYTE), 
	"MSG_SUBJECT3" VARCHAR2(4000 BYTE), 
	"MSG_GREETING1" VARCHAR2(4000 BYTE), 
	"MSG_GREETING2" VARCHAR2(4000 BYTE), 
	"MSG_TEXT1" VARCHAR2(4000 BYTE), 
	"MSG_TEXT2" VARCHAR2(4000 BYTE), 
	"MSG_TEXT3" VARCHAR2(4000 BYTE), 
	"MSG_TEXT4" VARCHAR2(4000 BYTE), 
	"MSG_TEXT5" VARCHAR2(4000 BYTE), 
	"MSG_TEXT6" VARCHAR2(4000 BYTE), 
	"MSG_ENDOFMAIL_MSG1" VARCHAR2(4000 BYTE), 
	"MSG_ENDOFMAIL_MSG2" VARCHAR2(4000 BYTE), 
	"MSG_ENDOFMAIL_MSG3" VARCHAR2(4000 BYTE), 
	"MSG_ENDOFMAIL_MSG4" VARCHAR2(4000 BYTE), 
	"MSG_ENDOFMAIL_MSG5" VARCHAR2(4000 BYTE), 
	"MAIL_SENT_TO" VARCHAR2(4000 BYTE), 
	"CR_ID" VARCHAR2(50 BYTE), 
	"CR_DT" TIMESTAMP (6), 
	"UPD_ID" VARCHAR2(50 BYTE), 
	"UPD_DT" TIMESTAMP (6), 
	"ACTIVE" VARCHAR2(2 BYTE), 
	"ACTIVATION_DT" TIMESTAMP (6), 
	"DEACTIVATION_DT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
REM INSERTING into HEIS_SU.UM_EMAIL_RESPONSE
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index UER_PK_RS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HEIS_SU"."UER_PK_RS_ID" ON "HEIS_SU"."UM_EMAIL_RESPONSE" ("RESPONSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
--------------------------------------------------------
--  Constraints for Table UM_EMAIL_RESPONSE
--------------------------------------------------------

  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("ORG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("RESPONSE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("MSG_SUBJECT1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("MSG_GREETING1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("MSG_TEXT1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("MSG_ENDOFMAIL_MSG1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("CR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("CR_DT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("ACTIVATION_DT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("DEACTIVATION_DT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" MODIFY ("MAIL_SENT_TO" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_EMAIL_RESPONSE" ADD CONSTRAINT "UER_PK_RS_ID" PRIMARY KEY ("RESPONSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS"  ENABLE;

