--------------------------------------------------------
--  File created - Friday-June-14-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UM_WORKFLOW_STAGES
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" 
   (	"ORG_ID" NUMBER(8,0), 
	"SOURCE_SYS_ID" NUMBER(8,0), 
	"MODULE_ID" NUMBER(8,0), 
	"MODULE_DESC1" VARCHAR2(4000 BYTE), 
	"MODULE_DESC2" VARCHAR2(4000 BYTE), 
	"WORKFLOWSTAGEID" VARCHAR2(50 BYTE), 
	"WORKFLOWID" VARCHAR2(50 BYTE), 
	"SEQNO" NUMBER(8,0), 
	"APPLSTAGE" VARCHAR2(50 BYTE), 
	"STAGE_DESC1" VARCHAR2(4000 BYTE), 
	"STAGE_DESC2" VARCHAR2(4000 BYTE), 
	"SRC_DESC1" VARCHAR2(4000 BYTE), 
	"SRC_DESC2" VARCHAR2(4000 BYTE), 
	"STAGE_CATEGORY_DESC1" VARCHAR2(4000 BYTE), 
	"STAGE_CATEGORY_DESC2" VARCHAR2(4000 BYTE), 
	"WORKFLOW_TYPE" VARCHAR2(100 BYTE), 
	"CATEGORY_SEQNO" NUMBER(2,0), 
	"STD_TAT_MINS" NUMBER(8,0), 
	"ESCALATION_ALERT_MINS" NUMBER(8,0), 
	"ACTION_COST" NUMBER(12,2), 
	"CR_ID" VARCHAR2(50 BYTE), 
	"CR_DT" DATE, 
	"UPD_ID" VARCHAR2(50 BYTE), 
	"UPD_DT" DATE, 
	"ACTIVE" VARCHAR2(2 BYTE), 
	"WS_ID" NUMBER(8,0), 
	"FIRST_LAST_IND" VARCHAR2(50 BYTE), 
	"TIMER_IN_MINS" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
 

   COMMENT ON COLUMN "HEIS_SU"."UM_WORKFLOW_STAGES"."FIRST_LAST_IND" IS 'This field will indicate whether this stage is the first one or the last one. There could be more than one start points or end points. Wherever this field is empty it indicates that the stage is neither first nor last!';
REM INSERTING into HEIS_SU.UM_WORKFLOW_STAGES
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index UWS_PK_WS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HEIS_SU"."UWS_PK_WS_ID" ON "HEIS_SU"."UM_WORKFLOW_STAGES" ("WS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
--------------------------------------------------------
--  Constraints for Table UM_WORKFLOW_STAGES
--------------------------------------------------------

  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("ORG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("SOURCE_SYS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("MODULE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("MODULE_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("WORKFLOWSTAGEID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("STAGE_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("SRC_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("STAGE_CATEGORY_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("CR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("CR_DT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("WS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" ADD CONSTRAINT "UWS_CHK_ACTIVE" CHECK ((ACTIVE IN ('Y','N')) ) ENABLE;
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" ADD CONSTRAINT "UWS_PK_WS_ID" PRIMARY KEY ("WS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS"  ENABLE;

