--------------------------------------------------------
--  File created - Sunday-June-02-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UM_WORKFLOW_STAGES
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" 
   (	"ORG_ID" NUMBER(8,0), 
	"SOURCE_SYS_ID" NUMBER(8,0), 
	"MODULE_ID" NUMBER(8,0), 
	"MODULE_DESC1" VARCHAR2(4000 BYTE), 
	"MODULE_DESC2" VARCHAR2(4000 BYTE), 
	"WORKFLOWSTAGEID" VARCHAR2(50 BYTE), 
	"WORKFLOWID" VARCHAR2(50 BYTE), 
	"SEQNO" NUMBER(8,0), 
	"APPLSTAGE" VARCHAR2(50 BYTE), 
	"STAGE_DESC1" VARCHAR2(4000 BYTE), 
	"STAGE_DESC2" VARCHAR2(4000 BYTE), 
	"SRC_DESC1" VARCHAR2(4000 BYTE), 
	"SRC_DESC2" VARCHAR2(4000 BYTE), 
	"STAGE_CATEGORY_DESC1" VARCHAR2(4000 BYTE), 
	"STAGE_CATEGORY_DESC2" VARCHAR2(4000 BYTE), 
	"WORKFLOW_TYPE" VARCHAR2(100 BYTE), 
	"CATEGORY_SEQNO" NUMBER(2,0), 
	"STD_TAT_MINS" NUMBER(8,0), 
	"ESCALATION_ALERT_MINS" NUMBER(8,0), 
	"ACTION_COST" NUMBER(12,2), 
	"CR_ID" VARCHAR2(50 BYTE), 
	"CR_DT" DATE, 
	"UPD_ID" VARCHAR2(50 BYTE), 
	"UPD_DT" DATE, 
	"ACTIVE" VARCHAR2(2 BYTE), 
	"WS_ID" NUMBER(8,0), 
	"FIRST_LAST_IND" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
 

   COMMENT ON COLUMN "HEIS_SU"."UM_WORKFLOW_STAGES"."FIRST_LAST_IND" IS 'This field will indicate whether this stage is the first one or the last one. There could be more than one start points or end points. Wherever this field is empty it indicates that the stage is neither first nor last!';
REM INSERTING into HEIS_SU.UM_WORKFLOW_STAGES
SET DEFINE OFF;
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',1,'DINIT_MAIL','Request Mail','?????? ???','Request Mail','?????? ???','EMAIL','EMAIL','CORPORATE-DISB',1,10,20,3,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',1,'F');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5101,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',2,'DSYSDE','Request Submit','?????? ????','Request Submit','?????? ????','EMAIL','EMAIL','CORPORATE-DISB',1,15,25,55,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',2,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',3,'DAPPR_REQ_MAIL','Approval Request Email','??????? ??????','Approval Request Email','??????? ??????','EMAIL','EMAIL','CORPORATE-DISB',1,10,20,25,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',3,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',4,'DDECISION_APP_MAIL','Decision (Approved over mail)','?????? ???????? ????','Decision (Approved)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-DISB',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',4,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',6,'DHOVER_ACCNT_MAIL','ACCOUNT HANDOVER MAIL','???????? ???????','ACCOUNT HANDOVER MAIL','???????? ???????','EMAIL','EMAIL','CORPORATE-DISB',1,10,10,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',6,'L');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',1,'PINIT_MAIL','Request Mail','?????? ???','Request Mail','?????? ???','EMAIL','EMAIL','CORPORATE-PLEDGE',1,10,20,3,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',7,'F');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5101,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',2,'PSYSDE','Request Submit','?????? ????','Request Submit','?????? ????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,15,25,55,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',8,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',3,'PAPPR_REQ_MAIL','Approval Request Email','??????? ??????','Approval Request Email','??????? ??????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,10,20,25,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',9,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',4,'PDECISION_APP_MAIL','Decision (Approved over mail)','?????? ???????? ????','Decision (Approved)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',10,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',6,'PHOVER_DP_MAIL','DP HANDOVER MAIL','??? DP ???? ??????','DP HANDOVER MAIL','??? DP ???? ??????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,10,10,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',12,'L');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',4,'DDECISION_REJ_MAIL','Decision (Rejected over mail)','?????? ???????? ????','Decision (Reject)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-DISB',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',13,'L');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5100,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',4,'PDECISION_REJ_MAIL','Decision (Rejected over mail)','?????? ???????? ????','Decision (Reject)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',15,'L');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5101,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',5,'DDECISION_APP_SYS','Decision (Approved in system)','?????? ???????? ????','Decision (Approved)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-DISB',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',5,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5101,90,'EMAIL(E2)','?????E2?','WFS01','WFID01',5,'DDECISION_REJ_SYS','Decision (Rejected in system)','?????? ???????? ????','Decision (Reject)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-DISB',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',14,'L');
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5101,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',5,'PDECISION_APP_SYS','Decision (Approved in system)','?????? ???????? ????','Decision (Approved)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',11,null);
Insert into HEIS_SU.UM_WORKFLOW_STAGES (ORG_ID,SOURCE_SYS_ID,MODULE_ID,MODULE_DESC1,MODULE_DESC2,WORKFLOWSTAGEID,WORKFLOWID,SEQNO,APPLSTAGE,STAGE_DESC1,STAGE_DESC2,SRC_DESC1,SRC_DESC2,STAGE_CATEGORY_DESC1,STAGE_CATEGORY_DESC2,WORKFLOW_TYPE,CATEGORY_SEQNO,STD_TAT_MINS,ESCALATION_ALERT_MINS,ACTION_COST,CR_ID,CR_DT,UPD_ID,UPD_DT,ACTIVE,WS_ID,FIRST_LAST_IND) values (9000,5101,90,'EMAIL(E2)','?????E2?','WFS01','WFID02',5,'PDECISION_REJ_SYS','Decision (Rejected in system)','?????? ???????? ????','Decision (Reject)','?????? ???????? ????','EMAIL','EMAIL','CORPORATE-PLEDGE',1,25,35,75,'HEIS',to_date('27-MAY-13','DD-MON-RR'),null,null,'Y',16,'L');
--------------------------------------------------------
--  DDL for Index UWS_PK_WS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "HEIS_SU"."UWS_PK_WS_ID" ON "HEIS_SU"."UM_WORKFLOW_STAGES" ("WS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
--------------------------------------------------------
--  Constraints for Table UM_WORKFLOW_STAGES
--------------------------------------------------------

  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("ORG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("SOURCE_SYS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("MODULE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("MODULE_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("WORKFLOWSTAGEID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("STAGE_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("SRC_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("STAGE_CATEGORY_DESC1" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("CR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("CR_DT" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" MODIFY ("WS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" ADD CONSTRAINT "UWS_CHK_ACTIVE" CHECK ((ACTIVE IN ('Y','N')) ) ENABLE;
 
  ALTER TABLE "HEIS_SU"."UM_WORKFLOW_STAGES" ADD CONSTRAINT "UWS_PK_WS_ID" PRIMARY KEY ("WS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS"  ENABLE;

