--------------------------------------------------------
--  File created - Thursday-August-22-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FS_BROKER_TURNOVER_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."FS_BROKER_TURNOVER_ANALYSIS" 
   (	"BROKER" VARCHAR2(7 BYTE), 
	"BROKER_NAME" VARCHAR2(24 BYTE), 
	"PORTFOLIO_CATEGORY" VARCHAR2(17 BYTE), 
	"PORTFOLIO_TYPE" VARCHAR2(29 BYTE), 
	"GROSS_VALUE_ON_PURCHASE" NUMBER(16,2), 
	"GROSS_BROKERAGE_ON_PURCHASE" NUMBER(16,2), 
	"GROSS_VALUE_ON_SALE" NUMBER(16,2), 
	"GROSS_BROKERAGE_ON_SALE" NUMBER(16,2), 
	"GROSS_VALUE_TOTAL" NUMBER(16,2), 
	"GROSS_BROKERAGE_TOTAL" NUMBER(16,2), 
	"GROSS_VALUE" NUMBER(16,2), 
	"GROSS_BROKERAGE" NUMBER(16,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
REM INSERTING into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS
SET DEFINE OFF;
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ABNAMRO','RBS EQUITIES (INDIA) LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',38184000,324240,0,0,38184000,324240,3.5,27.07);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ANGEL','ANGEL SECURITIES LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',999214000,829214.4,0,1044,999214000,830258.4,91.57,69.32);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('BRICS','BRICS SECURITIES LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',53834000,43246.4,0,0,53834000,43246.4,4.93,3.61);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ABNAMRO','RBS EQUITIES (INDIA) LTD','With Portfolio','HEXFUND03 HexGen Liquid Fund',1980000,11880,0,0,1980000,11880,0.97,5.48);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ANGEL','ANGEL SECURITIES LTD','With Portfolio','HEXFUND03 HexGen Liquid Fund',3990000,23940,0,0,3990000,23940,1.96,11.05);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('BRICS','BRICS SECURITIES LTD','With Portfolio','HEXFUND03 HexGen Liquid Fund',124000000,99200,0,0,124000000,99200,60.78,45.8);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ABNAMRO','RBS EQUITIES (INDIA) LTD','With Portfolio','HEXFUND03 HexGen Liquid Fund',39600000,31680,0,0,39600000,31680,19.41,14.63);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ANGEL','ANGEL SECURITIES LTD','With Portfolio','HEXFUND03 HexGen Liquid Fund',6390000,5112,0,0,6390000,5112,3.13,2.36);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('BRICS','BRICS SECURITIES LTD','With Portfolio','HEXFUND03 HexGen Liquid Fund',0,31680,0,0,0,31680,0,14.63);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ABNAMRO','RBS EQUITIES (INDIA) LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',4200000,3360,0,0,4200000,3360,2.06,1.55);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('ANGEL','ANGEL SECURITIES LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',19850000,3195.2,0,0,19850000,3195.2,9.73,1.48);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('BRICS','BRICS SECURITIES LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',3994000,3195.2,0,0,3994000,3195.2,1.96,1.48);
Insert into HEIS_SU.FS_BROKER_TURNOVER_ANALYSIS (BROKER,BROKER_NAME,PORTFOLIO_CATEGORY,PORTFOLIO_TYPE,GROSS_VALUE_ON_PURCHASE,GROSS_BROKERAGE_ON_PURCHASE,GROSS_VALUE_ON_SALE,GROSS_BROKERAGE_ON_SALE,GROSS_VALUE_TOTAL,GROSS_BROKERAGE_TOTAL,GROSS_VALUE,GROSS_BROKERAGE) values ('BRICS','BRICS SECURITIES LTD','Without Portfolio','HEXFUND06 HexGen FMP Series 1',0,3360,0,0,0,3360,0,1.55);


