--------------------------------------------------------
--  File created - Thursday-August-22-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FS_FUNDWISE_PORTFOLIO_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "HEIS_SU"."FS_FUNDWISE_PORTFOLIO_ANALYSIS" 
   (	"ASSET_CLASS" VARCHAR2(33 BYTE), 
	"SECURITY_NAME" VARCHAR2(60 BYTE), 
	"ASSET_CLASS_PORTFOLIO" NUMBER(4,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HDM_TBS" ;
REM INSERTING into HEIS_SU.FS_FUNDWISE_PORTFOLIO_ANALYSIS
SET DEFINE OFF;
Insert into HEIS_SU.FS_FUNDWISE_PORTFOLIO_ANALYSIS (ASSET_CLASS,SECURITY_NAME,ASSET_CLASS_PORTFOLIO) values ('CCIL - SGF Deposit Account','BIRLA SUN LIFE CASH PLUS-INSTITUTIONAL PREMIUM PLAN (GROWTH)',2);
Insert into HEIS_SU.FS_FUNDWISE_PORTFOLIO_ANALYSIS (ASSET_CLASS,SECURITY_NAME,ASSET_CLASS_PORTFOLIO) values ('EQU - Equity Shares','AXIS BANK LIMITED',34);
Insert into HEIS_SU.FS_FUNDWISE_PORTFOLIO_ANALYSIS (ASSET_CLASS,SECURITY_NAME,ASSET_CLASS_PORTFOLIO) values ('GSEC - Government Securities(GSE)','5.64% GOI  (MD 02/01/2019)',17);
Insert into HEIS_SU.FS_FUNDWISE_PORTFOLIO_ANALYSIS (ASSET_CLASS,SECURITY_NAME,ASSET_CLASS_PORTFOLIO) values ('MFU - Mutual Fund Units','KOTAK LIQUID-INSTITUTIONAL PREMIUM PLAN - (GROWTH)',8);
Insert into HEIS_SU.FS_FUNDWISE_PORTFOLIO_ANALYSIS (ASSET_CLASS,SECURITY_NAME,ASSET_CLASS_PORTFOLIO) values ('NCD - Non Convertible Debentures','10.05% NABARD (MD 11/06/2014)',37);


